### ISSUE TITLE
add eeID tab to the frontpage template

### ISSUE THREAD

**Issue by vohmar** [internetee/internet.ee#11]
![image](https://user-images.githubusercontent.com/7734747/133582214-6edea20a-195e-424f-8f79-c44cbf01301a.png)

need a new tab added to the front page of internet.ee template for the new eeID service.

**Comment by vohmar** [comment]
small issue - on hovering cursor over the new tab the tab turns white (is not visible any more)

![image](https://user-images.githubusercontent.com/7734747/133582652-42263cbe-85ba-4f1f-a834-bca98bfc3052.png)

**Comment by RainariSviiter** [comment]
![image](https://user-images.githubusercontent.com/79274568/134424998-c308ddd3-4c6f-4a84-97b6-41cb87f0db56.png)
Hover issue solved
