### ISSUE TITLE
WHOIS: incorrect handling of disputed status

### ISSUE THREAD

**Issue by vohmar** [internetee/internet.ee#13]
domains with just disputes status are displayed as registered even though they necessarily are not

for example:
bittrex.ee

rwhois response:
{"disclaimer":null,"status":["disputed"],"name":"bittrex.ee"}

but whois on internet.ee returns
![image](https://user-images.githubusercontent.com/7734747/133828582-e3518c80-09a2-4cec-9c45-ea872e51ba81.png)

correct response in this case where domain is not actually registered (no other data is returned by whois) would be to return message (similarly to blocked and reserved domains ie cache.ee)

et: on vaidlustatud
en: is disputed

**Comment by RainariSviiter** [comment]
![image](https://user-images.githubusercontent.com/79274568/134428396-a574f463-22d4-42f1-9c70-30948902f9a7.png)
Done
