### ISSUE TITLE
some whois result pages are missing the profile pic

### ISSUE THREAD

**Issue by vohmar** [internetee/internet.ee#16]
For some reason some of the whois result pages presented on internet.ee are missing the profile pic

ie: kfc.ee

![image](https://user-images.githubusercontent.com/7734747/138653011-15750555-afb4-4d11-9414-02aaf65be1fe.png)

while: järve.ee

![image](https://user-images.githubusercontent.com/7734747/138653116-6991b9ec-dbf6-400a-891c-c3dbf0a9a8f9.png)

and internet.ee

![image](https://user-images.githubusercontent.com/7734747/138653209-868f6c7a-d085-46d8-81b4-590714d1dd2a.png)

**Comment by RainariSviiter** [comment]
tehtud oktoobris

**Comment by vohmar** [comment]
nätieks see: 58.ee

**Comment by RainariSviiter** [comment]
@vohmar tundub, et mergemata on - devis töötab, vaatan üle
![image](https://user-images.githubusercontent.com/79274568/151160092-90ee8a52-2bf1-4ec5-afe6-36650905f884.png)

**Comment by RainariSviiter** [comment]
Parandus productionis
