### ISSUE TITLE
Captcha does not fit mobile screens

### ISSUE THREAD

**Issue by vohmar** [internetee/internet.ee#19]
The recaptcha v2 image puzzle does not fit mobile screens

Tested with Safari on iOS 15.1

portrait:
![image](https://user-images.githubusercontent.com/7734747/144076923-3c74a1a3-630e-4a63-b6b0-2842f78ce7e3.png)

landscape:
![image](https://user-images.githubusercontent.com/7734747/144077048-96f764c8-ad27-4c54-af39-01c96a1014e1.png)

on clicking the puzzle moves further behind the corner leaving some transparent box on the way of using the page

**Comment by RainariSviiter** [comment]
https://github.com/internetee/internet.ee/pull/21
