### ISSUE TITLE
One character domains return is invalid error

### ISSUE THREAD

**Issue by vohmar** [internetee/internet.ee#34]
The whois search on the internet.ee webpage returns "is invalid" error message for one character domain searches.

The one character domains are being released at the moment so they are either blocked, registered or in auction . whois.internet.ee returns correct output. Please remove special handing of one character domain searches and pars the whois results as any other valid domain name search.

**Comment by erkkipung** [comment]
Return this for example õnnelik.ee http://xn--nnelik-oxa.ee/) is free. However we're pretty sure if there might be any issue, this is BE issue since the BE is responsible to handle this data. Or give us a sample, when this error message is arriving.

**Comment by vohmar** [comment]
as said this is concerning single character domain names. For example this is the response from the BE:

https://whois.internet.ee/v1/%C3%B5.ee?locale=et
<img width="509" alt="image" src="https://github.com/internetee/internet.ee/assets/7734747/f2a10594-b53b-4a36-96ad-25883ad1c8f3">

and this is what users sees on out webpage:
<img width="1017" alt="image" src="https://github.com/internetee/internet.ee/assets/7734747/8af335c6-7f00-4fcc-8a96-07a77b9ea104">

**Comment by RainariSviiter** [comment]
![image](https://github.com/internetee/internet.ee/assets/79274568/3cd825ee-e58c-41b4-b85b-fecbb13713da)
Peaks olema korras

**Comment by vohmar** [comment]
Super, toimib, aitäh!
