### ISSUE TITLE
Searching for 1 character domains

### ISSUE THREAD

**Issue by vohmar** [internetee/internet.ee#35]
It's not possible to look for one character domains in the current domain search

![image](https://github.com/internetee/internet.ee/assets/7734747/16224309-f124-4c68-bcff-418baee8df25)

as now also 1 character domains are available we need to change this behavior and enable search with a single character as well

**Comment by RainariSviiter** [comment]
![image](https://github.com/internetee/internet.ee/assets/79274568/6d91bef4-b87e-42ec-8e47-2c28cf0b5a1a)
Palun vaadata

**Comment by vohmar** [comment]
korras, aitäh!
